### ISSUE TITLE
Design Models/Schema to support book info

### ISSUE THREAD

**Issue by breyerjs** [season89757/cosi166-learncoding#2]
Set up database so it can store information from Amazon, Goodreads, etc

**Comment by breyerjs** [comment]
@jaosn @season89757 @anboi1225 This is an example of tagging people on an issue comment. It's useful for talking about issues remotely.

**Comment by jaosn** [comment]
I think I am done with the schema, also define the relationship between models, I though we have some relationship by using through, but seems there is not or I might be misunderstanding it, we can have a discussion next meeting

**Comment by jaosn** [comment]
The reason I use scaffold for books is that we might want something like book/id(), but for users, I am not sure
